### PR TITLE
Fixes issue #48: suffix_extract extracts the domain wrong

### PR DESCRIPTION
**Pull request by mkhezr**

### CODE REVIEW

**Comment by okeyes-r7** [comment]
It looks like the unit tests failed (either because the code is producing the wrong output or because the tests need changing!) Did you run the testthat tests and all of that nonsense?

**Comment by Ironholds** [comment]
Okay, so from tinkering it looks like the solution is to actually leave that line as is, and instead change the trie constructor to accept `paste0(".", cleaned_suffixes)` for keys.

This produces, for the example:

```
suffix_extract(domain("http://www.converse.com"))
              host subdomain   domain suffix
1 www.converse.com       www converse    com
```

Bingo!

The problem is this _also_ makes it impossible to match where the suffix is the only thing in the domain (a trie can match .com to foo.com, but cannot match .foo.com to foo.com - it just produces .com). This bit was @jayjacobs addition, iirc, so I'd love his thoughts on this - is that an acceptable cost? In my mind the answer is 'yes', because misparsing anything ambiguous is a _much_ bigger problem than not being able to handle the relatively rare suffix-only domain names.

**Comment by alexcpsec** [comment]
Oh, I see your point. The thing is that those things are not that rare on larger web proxy datasets. I'd vote against not giving the "correct" answers. 

One (not very efficient) idea would be to do a first pass on the dataset to trivially return on those where suffix == domain? Then we would go to normal processing.

**Comment by Ironholds** [comment]
Ooh, so just domain %in% suffix set? That's an A+ idea.

**Comment by alexcpsec** [comment]
It _is_ O(n). What else can we hope for? ;)

**Pull request closed without merging**
