### PR TITLE
Add punycode support.

### PR DESCRIPTION
**Pull request by wrathematics**
# Quick summary

* Added but did not export (see notes) R function `make_puny()`. It is vectorized in the C source.
* Added full punycode source (with minor modifications); Ben Noordhuis would need to be listed as cph.
* Added a piece of [cutef8](https://github.com/JeffBezanson/cutef8/blob/master/utf8.c). It is public domain, so I don't think you have to name the author, but I feel like it's polite. Consider adding Jeff Bezanson as cph or ctb. Also see notes.

# Notes

* I can't `roxygenize()` for some reason; I get:
```
> roxygen2::roxygenize()
Loading required package: Rcpp
Loading required package: triebeard
Error in get(name, envir = env) : object 'suffix_dataset' not found
```
So you'll have to re-run that.

* I wrote a test `tests/punycode.R`. I didn't integrate it with testthat because it makes my eyes bleed. You can either leave it or integrate it.

* Tests were generated using the [RFC](http://www.faqs.org/rfcs/rfc3492.html), this [unicode converter](https://r12a.github.io/apps/conversion/), and this [punycode converter](https://www.charset.org/punycode.php).

* See line 49 of `src/punycode_wrapper.c`.

* This may break on non-Linux envs because of the memory conversions, so please test it thoroughly.

* It may be possible to change the cutef8 call `u8_toucs()` to the C99 function `mbstowcs()` if you can guarantee that `wchar_t` is `uint32_t` (this is not guaranteed, but you could configure test for it).  It worked for me, but also gave a significant compiler warning.

* Buffer sizes are set to 1024. Since this is for url's, I can't imagine that being a problem. But you could increase it to 4 or 8kb no problem. If you want to handle very general cases, memory will have to be managed dynamically.

### CODE REVIEW

**Comment by okeyes-r7** [comment]
OH MY GOD ARE YOU A WIZARD

**Comment by okeyes-r7** [comment]
Any chance decoding would be possible too, and where do you want me to send the {chocolate, beer, whiskey, you pick}

**Comment by wrathematics** [comment]
Sure, I can add decoding. I have classes and meetings for the next few hours, but I can get to it this weekend.

**Comment by wrathematics** [comment]
I don't think the decoder actually works. I can go into more details if you care, but I'm quite confident at this point that the decoder is broken.

Do you know of another license-compatible implementation? I could build one from the RFC, but it would take a while, and I'm looking for jobs at the moment, so no idea when I'd be able to get around to it.

**Comment by Ironholds** [comment]
Details might be good (that way we can open a bug report!) but probably not anything I can do aboot it :(

No other implementation I'm aware of (well, there's a JS one, but I've resisted porting that because that way madness lies). Ah well :(

**Comment by hrbrmstr** [comment]
y'all are avoiding libidn for Windows compat, I'm assuming? https://github.com/hrbrmstr/punycode

**Comment by wrathematics** [comment]
Well, I don't really know much about these tools/applications. Basically Oliver emailed me asking for advice on the char*/uint32* conversion, and I just went ahead and made a PR because this is pretty standard stuff for a C programmer ("C if nothing but void* and a pack of lies!" - a former colleague).

The js one mentions [this](http://opensource.apple.com/source/ICU/ICU-400.42/icuSources/common/punycode.c), which appears to be under a BSD-like (but not BSD) license, if my lawyer-dar is correct.  If it's license compatible, I could take a look at it.  Or maybe move it to hrbrmstr/punycode and import it in urltools?  I'll let you two figure that out.

For the current one, my tests are
```
bücher
세계의모든사람들이한국어를이해한다면얼마나좋을까
למההםפשוטלאמדבריםעברית
他們爲什麽不說中文
```
The first is from wikipedia, the other three are mentioned explicitly in the RFC.  These all encode correctly to
```
bcher-kva
989aomsvi5e83db1d2a355cv1e0vak1dwrv93d5xbh15a0dt30a5jpsd879ccm6fea98c
4dbcagdahymbxekheh6e0a7fei0b
ihqwctvzc91f659drss3x8bo0yb
```
"Correct" here means every web tool I can find agrees (except some start all punycode strings with `xn--`, which appears to be stylistic more than anything, as far as I can tell).  But when I try to decode these, I get:
```
bücher
ꆌꦃꅇꆯꆊꃃꦑꦃ餐ꆉꆮꆬꆫꉛꇀꃆꆮꆴꇀꆭꆍꆎꆞ馳ꆇ鲽ꆞꆏꆰꆰꃽꂿꆋ黬ꆪ骒ꆪꆯ
פטךאאפיבהט\u05ccךמ\u05cfפץ\u05cdץוין\u05cdו                        
他𨡃什𨿬伸𨥢不큙中
```
As you can see, only the first one is right, as I'm under the impression I should get my original inputs back.  It could be that I don't understand the inputs well enough and that the tests themselves don't make sense, but the various web tools seem to be able to handle them for the most part.  Anyway, I'll commit what I have and you can investigate it and see if it makes more sense under the kinds of inputs you're expecting.

**Comment by Ironholds** [comment]
https://dxr.mozilla.org/mozilla-central/source/netwerk/dns/punycode.c appears openly licensed and fairly similar. hmn.

**Comment by wrathematics** [comment]
Seems to work well.

**Comment by wrathematics** [comment]
I forgot to test on Windows. After converting the unicode in the test to its escape sequence equivalent, the encoding is correct, and the decoding up to the `uint8_t*` array is correct. But once converted back to a `char*` string, the chars are interpreted incorrectly or something.

I'm not a windows expert so I'm not sure if this is a potential problem with the converter `u8_toutf8()` (doubtful, as `wcstombs()` has weird issues as well) or if windows is just being windows, or what.

**Comment by hrbrmstr** [comment]
I recall Jeroen having to do some wrangling to get something similar to work correctly in Windows for JSON stuff (at least I think it was JSON parsing related). Might be worth reaching out.

**Comment by wrathematics** [comment]
Ok, I think I got it. You can declare the encoding on string creation directly from C. This seems to please Windows. Declaring a string UTF-8 from R is no good for whatever reason.

I'll push the updates in a minute.

**Comment by Ironholds** [comment]
Ho-leeeee shit.

**Pull request merged**
